const $=s=>document.querySelector(s);let token='',statusFilter='',tickets=[],current='',mailInfo={offices:{}};
const OFFICES=['教務處註冊組','教務處課務組','學務處生活輔導組','學務處住宿服務組','國際處','總務處','資訊處','圖資處','系辦公室','其他行政單位'];
const esc=v=>{const n=document.createElement('div');n.textContent=v??'';return n.innerHTML};const headers=()=>({'X-Admin-Token':token});
const officeLabel=document.createElement('label');officeLabel.innerHTML=`轉派／主管單位<select id="update-office">${OFFICES.map(x=>`<option>${x}</option>`).join('')}</select>`;$('#update-status').closest('label').before(officeLabel);
const hours=v=>`${(Number(v)||0).toFixed(1)} 小時`;
function renderStats(s){const score=s.rating_avg==null?'尚無評分':s.rating_avg.toFixed(1);
 $('#stats').innerHTML=`<article><span>提問總數</span><strong>${s.total_queries.toLocaleString()}</strong><small>最近 ${s.days} 天</small></article><article><span>轉單數（轉單率）</span><strong>${s.transfer_count.toLocaleString()}<em>${s.transfer_rate}%</em></strong><small>承辦處室實際轉出；改派 ${s.transferred_tickets} 張工單</small></article><article><span>已解決</span><strong>${s.ticket_resolved.toLocaleString()}</strong><small>待處理 ${s.ticket_pending}／處理中 ${s.ticket_processing}</small></article><article><span>平均解答時間</span><strong>${(s.avg_resolution_hours||0).toFixed(1)}<em>小時</em></strong><small>從建立到結案</small></article><article class="accent"><span>平均評分</span><strong>${score}<em class="star">★</em></strong><small>共 ${s.rating_count} 則評分</small></article>`;
 const maxTotal=Math.max(1,...s.tickets_by_office.map(x=>x.total)),maxHours=Math.max(1,...s.tickets_by_office.map(x=>x.avg_hours||0));
 $('#office-overview').innerHTML=s.tickets_by_office.length?'<div class="unit-row unit-head"><span>單位</span><span>問題數</span><span>平均解答時間（小時）</span><span>平均評分</span></div>'+s.tickets_by_office.map(x=>{const slow=(x.avg_hours||0)>=s.slow_hours;
  const cell=x.rating_avg==null?`<span class="score muted">樣本不足 <small>n=${x.rating_count}</small></span>`:`<span class="score">${x.rating_avg.toFixed(1)} <i>★</i> <small>n=${x.rating_count}</small></span>`;
  return `<div class="unit-row"><strong>${esc(x.office)}</strong><div class="bar"><i><b style="width:${Math.max(4,x.total/maxTotal*100)}%"></b></i><em>${x.total}</em></div><div class="bar"><i><b class="${slow?'slow':''}" style="width:${Math.max(4,(x.avg_hours||0)/maxHours*100)}%"></b></i><em class="${slow?'slow':''}">${(x.avg_hours||0).toFixed(1)}</em></div>${cell}</div>`}).join(''):'<p class="empty">目前期間沒有單位工單資料</p>';
 const maxCount=Math.max(1,...s.rating_distribution.map(x=>x.count));$('#rating-count').textContent=`共 ${s.rating_count} 則評分`;
 $('#rating-distribution').innerHTML=s.rating_distribution.map(x=>`<div class="rating-line"><span>${x.stars} ★</span><i><b class="${x.stars<=s.low_rating_max?'low':''}" style="width:${x.count/maxCount*100}%"></b></i><em>${x.count}</em></div>`).join('');
 $('#rating-note').innerHTML=`橘色為 1–2 星，會自動重啟提問單（目前 ${s.low_rating_count} 則）。${s.feedback_total?`<br>另有 ${s.feedback_total} 則 AI 回答回饋，好評率 ${s.helpful_rate}%。`:''}`;
 $('#pending-overview').innerHTML=s.pending_tickets.length?'<div class="pend-row pend-head"><span>提問單編號</span><span>分類</span><span>主責單位</span><span>已等待</span><span>狀態</span></div>'+s.pending_tickets.map(x=>`<button class="pend-row" data-view="${esc(x.ticket_no)}" title="${esc(x.subject)}"><span class="no">${esc(x.ticket_no)}</span><span>${esc(x.category)}</span><span>${esc(x.office)}</span><span class="wait ${x.overdue?'over':''}">${hours(x.waiting_hours)}</span><span><b class="badge ${x.overdue?'overdue':''}">${x.overdue?'逾期':esc(x.status)}</b></span></button>`).join(''):'<p class="empty">目前沒有待處理提問單</p>';
 $('#dash-foot').textContent=`資料期間：最近 ${s.days} 天 · 等待超過 ${s.overdue_hours} 小時標記逾期 · 統計更新於 ${s.generated_at}（台灣時間 UTC+8）`}
async function load(){const days=$('#days').value;const [sr,tr]=await Promise.all([fetch(`/api/admin/stats?days=${days}`,{headers:headers()}),fetch(`/api/admin/tickets?status=${encodeURIComponent(statusFilter)}&office=${encodeURIComponent($('#office-filter').value)}`,{headers:headers()})]);if(!sr.ok)throw new Error('管理密碼不正確');const s=await sr.json(),t=await tr.json();tickets=t.tickets;renderStats(s);if($('#office-filter').options.length===1)OFFICES.forEach(x=>$('#office-filter').add(new Option(x,x)));$('#count').textContent=`共 ${tickets.length} 筆`;$('#tickets').innerHTML=tickets.length?tickets.map(x=>`<tr><td>${esc(x.ticket_no)}</td><td><small>${esc(x.category)}</small>${esc(x.subject)}</td><td>${esc(x.office)}</td><td>${esc(x.created_at)}</td><td>${x.rating?`<span class="score">${x.rating} <i>★</i></span>`:'<span class="muted">未評分</span>'}</td><td><span class="badge ${x.status==='待處理'?'pending':''}">${esc(x.status)}</span></td><td><button class="view" data-view="${esc(x.ticket_no)}">查看 →</button></td></tr>`).join(''):'<tr><td colspan="7">目前沒有工單</td></tr>'}
function openDetail(no){const x=tickets.find(t=>t.ticket_no===no);if(!x)return;current=no;$('#detail-no').textContent=x.ticket_no;$('#detail-subject').textContent=x.subject;$('#detail-body').innerHTML=`<div class="detail-grid"><div><small>指定處室</small><p>${esc(x.office)}</p></div><div><small>分類</small><p>${esc(x.category)}</p></div><div><small>申請人</small><p>${esc(x.requester_name)}</p></div><div><small>聯絡方式</small><p>${esc(x.requester_contact)}</p></div><div><small>建立時間（台灣時間）</small><p>${esc(x.created_at)}</p></div><div><small>提問者評分</small><p>${x.rating?`${x.rating} ★${x.rating_comment?'　'+esc(x.rating_comment):''}<br><small>${esc(x.rated_at||'')}</small>`:'尚未評分'}</p></div></div><h3>問題內容</h3><p>${esc(x.description).replace(/\n/g,'<br>')}</p><p class="mail-line"><span>通知信：<strong class="${x.email_status==='sent'?'mail-on':'mail-off'}">${x.email_status==='sent'?'已寄出':x.email_status==='failed'?'寄送失敗（'+esc(x.email_error)+'）':'尚未寄出'}</strong></span><button type="button" class="resend" data-resend="${esc(x.ticket_no)}">重寄通知信</button></p>`;$('#update-office').value=x.office;$('#update-status').value=x.status;$('#update-assignee').value=x.assignee;$('#update-resolution').value=x.resolution;$('#detail').showModal()}
$('#login-form').onsubmit=async e=>{e.preventDefault();token=$('#token').value;try{await load();await loadMail();$('#login').hidden=true;$('#dashboard').hidden=false}catch(err){$('#login-error').textContent=err.message}};
document.addEventListener('click',e=>{const f=e.target.closest('[data-status]');if(f){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');statusFilter=f.dataset.status;load()}const v=e.target.closest('[data-view]');if(v)openDetail(v.dataset.view)});$('#days').onchange=load;$('#office-filter').onchange=load;$('#detail-close').onclick=()=>$('#detail').close();
$('#update-form').onsubmit=async e=>{e.preventDefault();const r=await fetch(`/api/admin/tickets/${current}`,{method:'PATCH',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({status:$('#update-status').value,office:$('#update-office').value,assignee:$('#update-assignee').value,resolution:$('#update-resolution').value})});if(!r.ok)return alert('儲存失敗');$('#detail').close();load()};
$('#export').onclick=async()=>{if(!token)return alert('請先登入');const r=await fetch('/api/admin/tickets.csv',{headers:headers()}),b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='tickets.csv';a.click();URL.revokeObjectURL(a.href)};
const mailMsg=(text,ok)=>{const el=$('#mail-message');el.textContent=text;el.className=ok?'ok':'err'};function renderOfficeMails(){$('#office-mails').innerHTML=OFFICES.map(o=>`<label>${esc(o)}<input type="email" data-office="${esc(o)}" value="${esc((mailInfo.offices||{})[o]||mailInfo.default_email||'')}"></label>`).join('')}
async function loadMail(){const r=await fetch('/api/admin/mail/settings',{headers:headers()});if(!r.ok)throw new Error('管理密碼不正確');mailInfo=await r.json();$('#mail-server').value=mailInfo.method==='gmail_oauth'?'Gmail OAuth':(mailInfo.server||'SMTP');$('#mail-port').value=mailInfo.port||587;$('#mail-username').value=mailInfo.sender||'';$('#mail-from-name').value=mailInfo.from_name||'校務 FAQ 工單系統';$('#mail-password').value='';$('#mail-state').innerHTML=mailInfo.configured?'<span class="mail-on">● 寄信已啟用</span>':'<span class="mail-off">● 尚未啟用</span>';renderOfficeMails()}
function mailPayload(){return{server:mailInfo.server||'smtp.gmail.com',port:Number(mailInfo.port||587),username:mailInfo.sender||'',from_name:$('#mail-from-name').value.trim()||'校務 FAQ 工單系統',password:'',offices:Object.fromEntries([...document.querySelectorAll('[data-office]')].map(i=>[i.dataset.office,i.value.trim()||mailInfo.default_email]))}}
$('#mail-form').onsubmit=async e=>{e.preventDefault();mailMsg('儲存中…',true);const r=await fetch('/api/admin/mail/settings',{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify(mailPayload())});const d=await r.json().catch(()=>({}));if(!r.ok)return mailMsg(d.detail||'儲存失敗',false);mailInfo=d;await loadMail();mailMsg('已儲存，之後工單會寄到上列信箱。',true)};$('#mail-reset').onclick=()=>{document.querySelectorAll('[data-office]').forEach(i=>i.value=mailInfo.default_email||'');mailMsg('已填回預設信箱，記得按「儲存設定」。',true)};
$('#mail-test').onclick=async()=>{const to=prompt('測試信要寄到哪個信箱？',mailInfo.default_email||'');if(!to)return;mailMsg('寄送中…',true);const r=await fetch('/api/admin/mail/test',{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({to})});const d=await r.json().catch(()=>({}));mailMsg(r.ok?`測試信已寄至 ${d.to}`:(d.detail||'測試信寄送失敗'),r.ok)};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-resend]');if(!b)return;b.disabled=true;b.textContent='寄送中…';const r=await fetch(`/api/admin/tickets/${encodeURIComponent(b.dataset.resend)}/resend-mail`,{method:'POST',headers:headers()});const d=await r.json().catch(()=>({}));b.textContent='重寄通知信';b.disabled=false;alert(r.ok?`通知信已寄至 ${d.to}`:(d.detail||'寄送失敗'));await load()});
