const ticketStyle=document.createElement('link');ticketStyle.rel='stylesheet';ticketStyle.href='/static/ticket.css?v=20260908172342';document.head.appendChild(ticketStyle);const $=s=>document.querySelector(s),form=$('#search-form'),input=$('#query'),button=$('#submit'),statusEl=$('#status'),conversation=$('#conversation'),ticketDialog=$('#ticket-dialog'),ticketForm=$('#ticket-form');const HISTORY_KEY='school-faq-conversations-v3';let lastQuery='';
function esc(v){const n=document.createElement('div');n.textContent=v??'';return n.innerHTML}function rich(v){return esc(v).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}function scroll(){requestAnimationFrame(()=>conversation.scrollTo({top:conversation.scrollHeight,behavior:'smooth'}))}
function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}function renderHistory(){const h=loadHistory();$('#history-list').innerHTML=h.length?h.map((x,i)=>`<button class="history-item" data-history="${i}"><span>${esc(x.query)}</span><small>${esc(x.time)}</small></button>`).join(''):'<p class="history-empty">尚無對話紀錄</p>'}function remember(q,d){const h=loadHistory();h.unshift({query:q,data:d,time:new Date().toLocaleString('zh-TW')});localStorage.setItem(HISTORY_KEY,JSON.stringify(h.slice(0,30)));renderHistory()}
function user(q){lastQuery=q;conversation.insertAdjacentHTML('beforeend',`<div class="message-row user-row"><div class="message user-message"><p>${esc(q)}</p></div><div class="avatar user-avatar">你</div></div>`);scroll()}function ticketConfirm(q){return `<section class="ticket-callout"><div><strong>${esc(scText('ticket_prompt_title','知識庫沒有這個問題，是否提出詢問單？'))}</strong><p>${esc(scText('ticket_prompt_text','確認後，AI 會依問題內容自動判斷並送至適合的處室。'))}</p></div><button type="button" data-ticket="${esc(q)}">${esc(scText('ticket_prompt_button','確認提出詢問單 →'))}</button></section>`}
function answer(d,q){if(!d.results?.length){conversation.insertAdjacentHTML('beforeend',`<div class="message-row assistant-row"><div class="avatar">AI</div><div class="answer-stack"><div class="message assistant-message"><p class="message-title">${esc(scText('no_answer_title','目前知識庫沒有這個問題'))}</p><p>${esc(scText('no_answer_text','您可以提出詢問單，由承辦處室協助回覆。'))}</p></div>${ticketConfirm(q)}</div></div>`);return scroll()}const cards=d.results.map(x=>`<article class="answer-card secondary-answer"><div class="answer-topline"><span>${esc(x.category||'FAQ')}</span><strong>${Math.round(x.score*100)}% 相符</strong></div><h2>${esc(x.question)}</h2><p class="answer-text">${rich(x.answer)}</p>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">開啟原始資料 ↗</a>`:''}<div class="feedback" data-question="${esc(x.question)}" data-query-text="${esc(q)}"><span>這個回答有幫助嗎？</span><button data-feedback="yes">👍</button><button data-feedback="no">👎</button></div></article>`).join('');conversation.insertAdjacentHTML('beforeend',`<div class="message-row assistant-row"><div class="avatar">AI</div><div class="answer-stack"><article class="answer-card ai-answer"><div class="answer-topline">${d.generated?`<span data-sc="answer_ai_label">${esc(scText('answer_ai_label','AI 整理'))}</span>`:`<span data-sc="answer_faq_label">${esc(scText('answer_faq_label','FAQ 原文'))}</span>`}</div><p class="answer-text">${rich(d.answer)}</p></article><details class="sources"><summary>查看參考 FAQ（${d.results.length}）</summary><div class="source-cards">${cards}</div></details></div></div>`);scroll()}
async function ask(q){q=q.trim();if(!q||button.disabled)return;user(q);input.value='';button.disabled=input.disabled=true;statusEl.textContent='正在搜尋 FAQ 並整理回答…';try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,limit:5})}),d=await r.json();if(!r.ok)throw new Error(d.detail||'服務暫時無法使用');answer(d,q);remember(q,d);statusEl.textContent=''}catch(e){conversation.insertAdjacentHTML('beforeend',`<div class="message-row assistant-row"><div class="avatar">!</div><div class="message error"><p>${esc(e.message)}</p></div></div>`)}finally{button.disabled=input.disabled=false;input.focus();scroll()}}
function openTicket(q){lastQuery=q;$('#ticket-subject').value=q;$('#ticket-description').value=`原始提問：${q}\n\n補充說明：`;$('#ticket-status').textContent='AI 將在送出後自動判斷承辦處室。';ticketDialog.showModal()}async function submitTicket(e){e.preventDefault();const send=ticketForm.querySelector('.primary');send.disabled=true;$('#ticket-status').textContent=scText('ticket_creating','AI 正在判斷承辦處室並建立詢問單…');const body={query:lastQuery,office:'',category:'其他',subject:$('#ticket-subject').value.trim(),description:$('#ticket-description').value.trim(),requester_name:$('#ticket-name').value.trim(),requester_contact:$('#ticket-contact').value.trim()};try{const r=await fetch('/api/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.detail||'建立失敗');ticketForm.innerHTML='<div class="ticket-success"><span>✓</span><h2>已提交</h2><p>問題已交由承辦處室處理。</p></div>'}catch(err){$('#ticket-status').textContent=err.message;send.disabled=false}}
let pendingTicket=null;function openEmailThenSubmit(q,trigger){pendingTicket={q,trigger};document.querySelector('#email-input').value='';document.querySelector('#email-status').textContent='';document.querySelector('#email-dialog').showModal()}async function submitAnonymousTicket(q,trigger,email){const callout=trigger.closest('.ticket-callout');trigger.disabled=true;trigger.textContent='正在提交…';const body={query:q,office:'',category:'其他',subject:q,description:`原始提問：${q}`,requester_name:'學生',requester_contact:email||'未提供'};try{const r=await fetch('/api/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.detail||'建立失敗');callout.innerHTML='<div class="submitted-ticket"><strong>✓ 已提交</strong><p>問題已交由承辦處室處理。</p></div>'}catch(err){trigger.disabled=false;trigger.textContent=scText('ticket_prompt_button','確認提出詢問單 →');callout.querySelector('p').textContent=err.message}}
const CATEGORY_LIMIT=8;let categoryMap=new Map();
function catLabel(name){const base=name.replace(/^[一二三四五六七八九十百]+、/,'').trim()||name,rows=window.scCategoryOverride?window.scCategoryOverride():[];for(const r of rows){const key=String(r.query||r.label||'');if(key===name||key===base)return r.label}return base}
function scText(key,fallback){const t=window.SITE_CONFIG&&window.SITE_CONFIG.text;return(t&&t[key])||fallback}
function pad(i){return String(i+1).padStart(2,'0')}
function renderCategories(list){const nav=$('#category-list');if(!nav||!list.length)return;nav.innerHTML=list.map((c,i)=>`<button class="category" data-category="${esc(c.category)}"><span>${pad(i)}</span>${esc(catLabel(c.category))}</button>`).join('')}
async function loadCategories(){try{await(window.SITE_CONFIG_READY||Promise.resolve());const r=await fetch(`/api/categories?limit=${CATEGORY_LIMIT}`);if(!r.ok)return;const d=await r.json(),list=d.categories||[];if(!list.length)return;categoryMap=new Map(list.map(c=>[c.category,c]));renderCategories(list)}catch{}}
function markActive(name){document.querySelectorAll('#category-list .category').forEach(b=>b.classList.toggle('active',b.dataset.category===name))}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#sidebar-backdrop').hidden=true}
function showCategory(name){const c=categoryMap.get(name);if(!c||!c.questions?.length)return ask(`${catLabel(name)}常見問題`);markActive(name);closeSidebar();const label=catLabel(name),more=c.total>c.questions.length?`<p class="faq-picker-more">此分類共 ${c.total} 題，以下列出 ${c.questions.length} 題常見問題。</p>`:'';conversation.insertAdjacentHTML('beforeend',`<div class="message-row assistant-row"><div class="avatar">AI</div><div class="answer-stack"><section class="faq-picker"><div class="faq-picker-head"><span>${esc(label)}</span><strong>請選擇想問的問題</strong></div><div class="faq-picker-list">${c.questions.map((q,i)=>`<button type="button" class="faq-pick" data-example="${esc(q)}"><em>${pad(i)}</em><span>${esc(q)}</span></button>`).join('')}</div>${more}<p class="faq-picker-hint">沒有想問的？直接在下方輸入你的問題即可。</p></section></div></div>`);scroll()}
function newChat(){conversation.innerHTML=`<div class="message-row assistant-row"><div class="avatar">AI</div><div class="message assistant-message"><p class="message-title">${esc(scText('welcome_title','您好，我是校務 FAQ 助理'))}</p><p>${esc(scText('newchat_welcome_text','請輸入您的問題；知識庫沒有答案時，您可以確認提出詢問單。'))}</p></div></div>`;statusEl.textContent='';markActive('');input.focus()}
form.addEventListener('submit',e=>{e.preventDefault();ask(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});ticketForm.addEventListener('submit',submitTicket);$('#ticket-close').onclick=$('#ticket-cancel').onclick=()=>ticketDialog.close();$('#new-chat').onclick=$('#mobile-new-chat').onclick=newChat;$('#menu-toggle').onclick=()=>{$('#sidebar').classList.add('open');$('#sidebar-backdrop').hidden=false};$('#menu-close').onclick=$('#sidebar-backdrop').onclick=()=>{$('#sidebar').classList.remove('open');$('#sidebar-backdrop').hidden=true};$('#clear-history').onclick=()=>{if(confirm('確定清除對話紀錄？')){localStorage.removeItem(HISTORY_KEY);renderHistory()}};
document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat)showCategory(cat.dataset.category);const c=e.target.closest('[data-query],[data-example]');if(c)ask(c.dataset.query||c.dataset.example);const t=e.target.closest('[data-ticket]');if(t)openEmailThenSubmit(t.dataset.ticket,t);const h=e.target.closest('[data-history]');if(h){const x=loadHistory()[Number(h.dataset.history)];if(x){user(x.query);answer(x.data,x.query)}}const f=e.target.closest('[data-feedback]');if(f){const w=f.closest('.feedback');w.querySelector('span').textContent=f.dataset.feedback==='yes'?'謝謝您的回饋':'謝謝回饋，我們會持續改善知識庫';fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:w.dataset.queryText,source_question:w.dataset.question,helpful:f.dataset.feedback==='yes'})}).catch(()=>{})}});renderHistory();loadCategories();

;(function(){var ef=document.querySelector('#email-form');if(!ef)return;var ed=document.querySelector('#email-dialog'),ei=document.querySelector('#email-input'),es=document.querySelector('#email-status');document.querySelector('#email-close').onclick=document.querySelector('#email-cancel').onclick=function(){ed.close()};ef.addEventListener('submit',function(e){e.preventDefault();var v=ei.value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)){es.textContent='請輸入正確的電子郵件';return}if(!pendingTicket)return;ed.close();submitAnonymousTicket(pendingTicket.q,pendingTicket.trigger,v);pendingTicket=null})})();
