const $=s=>document.querySelector(s);let token=sessionStorage.getItem('office-token')||'',status='';
const esc=v=>{const n=document.createElement('div');n.textContent=v??'';return n.innerHTML};
const headers=()=>({'X-Office-Token':token});
async function loadMail(){const r=await fetch('/api/office/mail',{headers:headers()}),d=await r.json();if(!r.ok)throw new Error(d.detail||'無法讀取信箱設定');$('#office-email').value=d.email||d.default_email||''}
async function load(){const r=await fetch(`/api/office/tickets?status=${encodeURIComponent(status)}`,{headers:headers()}),d=await r.json();if(!r.ok)throw new Error(d.detail||'登入失敗');sessionStorage.setItem('office-token',token);$('#login').hidden=true;$('#queue').hidden=false;$('#office-name').textContent=d.office;$('#summary').textContent=`共 ${d.tickets.length} 張工單`;$('#tickets').innerHTML=d.tickets.length?d.tickets.map(x=>`<a class="ticket" href="/office/ticket/${encodeURIComponent(x.ticket_no)}"><b>${esc(x.ticket_no)}</b><div><small>${esc(x.category)}</small><strong>${esc(x.subject)}</strong></div><span class="badge">${esc(x.status)}</span><b>開啟回覆 →</b></a>`).join(''):'<div class="ticket">目前沒有工單</div>';await loadMail()}
$('#office-mail-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter,message=$('#office-mail-message');button.disabled=true;message.className='';message.textContent='儲存中…';const r=await fetch('/api/office/mail',{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({email:$('#office-email').value.trim()})}),d=await r.json().catch(()=>({}));button.disabled=false;message.textContent=r.ok?`已儲存：${d.email}`:(d.detail||'儲存失敗');message.className=r.ok?'ok':'err'};
$('#login-form').onsubmit=async e=>{e.preventDefault();token=$('#token').value;try{await load()}catch(err){$('#error').textContent=err.message}};
document.addEventListener('click',e=>{const f=e.target.closest('[data-status]');if(f){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');status=f.dataset.status;load()}});
$('#logout').onclick=()=>{sessionStorage.removeItem('office-token');location.reload()};if(token)load().catch(()=>sessionStorage.removeItem('office-token'));
