const $=s=>document.querySelector(s),parts=location.pathname.split('/'),ticketNo=decodeURIComponent(parts.at(-1)),params=new URLSearchParams(location.search);let key=params.get('key')||localStorage.getItem(`ticket-key-${ticketNo}`)||'';const esc=v=>{const n=document.createElement('div');n.textContent=v??'';return n.innerHTML};let picked=Math.min(5,Math.max(0,Number(params.get('rating'))||0));
const EVENT_LABEL={transfer:'轉派單位',reply:'提問者補充',update:'處理更新',rating:'提問者評分',reopen:'系統重啟',email:'系統通知'};
function renderStars(){$('#stars').innerHTML=[1,2,3,4,5].map(n=>`<button type="button" class="star ${n<=picked?'on':''}" data-star="${n}" aria-label="${n} 星">★</button>`).join('');$('#rate-submit').disabled=!picked}
function renderRating(t){const card=$('#rate-card'),done=t.status==='已解決';card.hidden=!done&&!t.rating;if(card.hidden)return;if(t.rating&&!picked)picked=t.rating;renderStars();
 $('#rate-hint').textContent=t.rating?`您已在 ${t.rated_at} 給予 ${t.rating} 星。若情況有變可重新評分。`:'承辦單位已結案，請給 1～5 星評價。1～2 星會自動重啟提問單，再請單位確認一次。';
 if(t.rating&&!$('#rate-comment').value)$('#rate-comment').value=t.rating_comment||'';$('#rate-submit').disabled=!picked||!done;if(!done)$('#rate-hint').textContent=`提問單目前為「${t.status}」，處理完成後即可再次評分。`}
function render(t){$('#loading').hidden=true;$('#content').hidden=false;$('#ticket-no').textContent=t.ticket_no;$('#status-badge').textContent=t.status;$('#office').textContent=$('#current-office').textContent=t.office;$('#subject').textContent=t.subject;$('#description').textContent=t.description;$('#meta').textContent=`分類：${t.category} · ${t.created_at}`;$('#events').innerHTML=t.events.length?t.events.map((e,i)=>`<div class="event ${i===t.events.length-1?'latest':''}"><strong>${esc(e.actor)} · ${esc(EVENT_LABEL[e.event_type]||'系統開單')}</strong><p>${esc(e.message)}</p><small>${esc(e.created_at)}${e.office?' · '+esc(e.office):''}</small></div>`).join(''):'<p>尚無處理紀錄</p>';renderRating(t)}
async function load(){if(!key){$('#loading').innerHTML='<p class="error">缺少工單存取碼，請使用建立工單後取得的完整連結。</p>';return}const r=await fetch(`/api/tickets/${encodeURIComponent(ticketNo)}?key=${encodeURIComponent(key)}`),d=await r.json();if(!r.ok){$('#loading').innerHTML=`<p class="error">${esc(d.detail||'無法讀取工單')}</p>`;return}render(d)}
$('#stars').onclick=e=>{const b=e.target.closest('[data-star]');if(!b)return;picked=Number(b.dataset.star);renderStars()};
$('#rate-submit').onclick=async e=>{if(!picked)return;e.currentTarget.disabled=true;$('#rate-status').textContent='正在送出…';const r=await fetch(`/api/tickets/${encodeURIComponent(ticketNo)}/rating`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({access_key:key,rating:picked,comment:$('#rate-comment').value.trim()})}),d=await r.json();if(r.ok){$('#rate-status').textContent=picked<=2?'已收到評分，提問單已自動重啟，承辦單位會再確認。':'感謝您的評分！';render(d)}else{$('#rate-status').textContent=d.detail||'評分失敗';e.currentTarget.disabled=false}};
$('#reply-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;$('#reply-status').textContent='正在送出…';const r=await fetch(`/api/tickets/${encodeURIComponent(ticketNo)}/replies`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({access_key:key,message:$('#reply').value.trim(),allow_faq:$('#allow-faq').checked})}),d=await r.json();if(r.ok){$('#reply').value='';$('#reply-status').textContent='補充內容已送出';render(d)}else $('#reply-status').textContent=d.detail||'送出失敗';b.disabled=false};load();
